### ISSUE TITLE
Documentation of effects

### ISSUE THREAD

**Issue by triska** [JanWielemaker/reindent#2]
Please consider adding more information about how reindenting many Prolog source files with this tool has affected various workflows.

For example, in the [7.4 roadmap](https://github.com/SWI-Prolog/swipl-devel/wiki/roadmap740), you write:

> ... such reformatting will break `git diff` and `git blame` even if `-b/-w` are used.

In my own use cases, this effect alone prevents me from doing such a mass conversion.

Is there anything else you experienced?

**Comment by JanWielemaker** [comment]
I guess there is enough documentation about the effect of reformatting code wrt patch workflows.   Tools such as `clang-format` (in fact most C reformatters) to change between 0 and 1 or more spaces/tabs
between e.g., function symbol and arguments and thus break glt, even with `-b/-w`.   This reformatter only moves the `!`, which affects git workflows.   That is typically good enough for me as I'm mostly interested in "how this code got into its present state?" in the case it looks odd.   We'll see, but I doubt
this will cause many issues.
